### ISSUE TITLE
please update bootprint version to 0.10.0

### ISSUE THREAD

**Issue by hlcq** [mitsuruog/api-first-spec-to-swagger#4]
# Problem
Mitzさん、お久しぶりです。
- current bootprint version get error. Please update to 0.10.0. Thank you
```js
start processing
patterns: ./src/specs/api/track/auth/signin.spec.js
output dir: ./src/docs/api/track/auth/signin
convert to swagger JSON
processing >> ./src/specs/api/track/auth/signin.spec.js
convert to swagger JSON completed.
generate API doc
Loading bootprint-openapi 0.16.0
Loading bootprint-json-schema 0.8.6
Loading bootprint-base 0.8.0
/usr/local/lib/node_modules/apifs2swagger/node_modules/customize/index.js:176
        throw new Error("Engine '" + engineName + "' not found. Refusing to store configuration")
        ^

Error: Engine 'uglify' not found. Refusing to store configuration
    at /usr/local/lib/node_modules/apifs2swagger/node_modules/customize/index.js:176:15
    at /usr/local/lib/node_modules/apifs2swagger/node_modules/lodash/index.js:3395:24
    at /usr/local/lib/node_modules/apifs2swagger/node_modules/lodash/index.js:3073:15
    at baseForOwn (/usr/local/lib/node_modules/apifs2swagger/node_modules/lodash/index.js:2046:14)
    at Function.mapValues (/usr/local/lib/node_modules/apifs2swagger/node_modules/lodash/index.js:3394:9)
    at Customize.merge (/usr/local/lib/node_modules/apifs2swagger/node_modules/customize/index.js:173:32)
    at module.exports (/usr/local/lib/node_modules/apifs2swagger/node_modules/bootprint-base/index.js:7:18)
    at Customize.load (/usr/local/lib/node_modules/apifs2swagger/node_modules/customize/index.js:238:12)
    at module.exports (/usr/local/lib/node_modules/apifs2swagger/node_modules/bootprint-json-schema/index.js:6:6)
    at Customize.load (/usr/local/lib/node_modules/apifs2swagger/node_modules/customize/index.js:238:12)
```

# Reference
https://github.com/bootprint/bootprint-base/issues/1

**Comment by mitsuruog** [comment]
@lecaoquochung It has been a while! 
I pushed a patch for this error. please try it later on. 
Thanks!
